title: ViLLM
description: "Crossing Linguistic Horizons: Finetuning and Comprehensive Evaluation of Vietnamese Large Language Models"

# disabled because we are using a custom domain
# baseurl: /

color-primary: "#B1040E"
color-light: "#E50808"
color-dark: "#820000"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
