name: Update Results

on:
  push:
    paths:
      - 'results/*.json'  # Trigger workflow when JSON files in 'results' are changed

jobs:
  update-yamls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Or your desired Python version

      - name: Run processing script
        run: python script/processing_result.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update YAML results'
          file_pattern: '_data/'